string1= "Mountains".upper()
print(string1)
string2="Captain and I are best company".split()
print(string2)
string3=" Hello , my man ".strip()
print(string3)
string4="   Good Afternoon, my lady ".rstrip()
print(string4)
string5=" 😋 ".join(['This','is','ummy','and','tasty'])
print(string5)